# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: vertical-pod-autoscaler-operator
    app.kubernetes.io/part-of: vertical-pod-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
  - path: /metrics
    port: https  # Ensure this is the name of the port that exposes HTTPS metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      ca: {}
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      cert: {}
    serverName: vpa-operator-metrics.openshift-vertical-pod-autoscaler.svc
  selector:
    matchLabels:
      control-plane: controller-manager
