apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpa-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpa-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: vertical-pod-autoscaler-operator
  namespace: openshift-vertical-pod-autoscaler
